### PR TITLE
expose bindings with leidenAlgAPI.h

### PR DESCRIPTION
**Pull request by theAeon**
Hey all-I wrote this semi-hack for the purpose of calling your wrapper from liger and I figured I'd contribute it back so that it can be included the proper way. Let me know if you have any questions-I'm sure that there's improvements to be had.

### CODE REVIEW

**Comment by evanbiederstedt** [comment]
Hi @theAeon 

Send my greetings to the Welch Lab! We're a fan!

Thanks for this.

I guess, I'm trying to figure out the use case. Wouldn't it make more sense to make this package a dependency in liger? 

Or just take the C code and put it your own package? https://github.com/kharchenkolab/leidenAlg/blob/main/src/RcppExports.cpp

Normally, I'm happy to include most things (if they pass CRAN standards) but this is a header file to call the function already compiled in this function. Why not just use that function from R? 

Best, Evan

**Comment by theAeon** [comment]
Hi! Appreciate the fast response. The reason to call it from a header file in `inst/include` is that we can call into it from our Rcpp code which will avoid unnecessary data shuttling between C++ and R. While we could include the c code directly, I'd rather not add the compilation time, binary size, and maintenance burden if I don't have to.

Its looking increasingly likely that I'm going to need to export all of the functions _called_ by find-graph for modification purposes, so it may make more sense to pull-request directly.

-Andrew

**Comment by evanbiederstedt** [comment]
Hi @theAeon 

I'm still a bit confused. 

Why couldn't use use this package and simply call the function from R? The package is on CRAN, and the function in your header file already exists from this package, no? 

> The reason to call it from a header file in inst/include is that we can call into it from our Rcpp code which will avoid unnecessary data shuttling between C++ and R.

What I'm saying is, the R code should just be this: 
https://github.com/kharchenkolab/leidenAlg/blob/main/R/RcppExports.R#L23-L25

`leidenAlg::find_partition_rcpp()` should work in R

Let me know what I'm missing. Best, Evan

**Comment by theAeon** [comment]
Yeah, I think you're right. The original intent was to wrap it with more functionality, but that's better served with a direct pull request-which my colleague submitted under #17

**Pull request closed without merging**
